import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const colors = {
  primary: '#e41c26',
  primaryLight: '#ff4d54',
  primaryDark: '#b81219',
  secondary: '#ff6b00',
  secondaryLight: '#ff8533',
  background: '#F8F9FA',
  cardBackground: '#FFFFFF',
  text: '#2D3748',
  textLight: '#718096',
  textDark: '#1A202C',
  border: '#E2E8F0',
  success: '#48BB78',
  info: '#4299E1',
  shadow: '#000',
};

const shadows = {
  small: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  medium: {
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#e41c26'
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    padding: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#2D3748',
    fontWeight: '500',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#E53E3E',
    textAlign: 'center',
    lineHeight: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
    backgroundColor: colors.cardBackground,
    padding: 15,
    borderRadius: 15,
    ...shadows.small,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 15,
    flex: 1,
  },
  selectedNames: {
    backgroundColor: `${colors.primary}08`,
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
  },
  selectedName: {
    fontSize: 16,
    color: colors.text,
    marginBottom: 8,
    fontWeight: '500',
  },
  alert: {
    backgroundColor: colors.cardBackground,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    ...shadows.small,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 6,
  },
  alertDescription: {
    fontSize: 14,
    color: colors.textLight,
    lineHeight: 20,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: `${colors.primary}15`,
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: colors.cardBackground,
    borderRadius: 10,
    ...shadows.small,
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textLight,
  },
  activeTabText: {
    color: colors.primary,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    ...shadows.medium,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 15,
  },
  topDeliverymanContainer: {
    marginTop: 15,
    backgroundColor: `${colors.primary}08`,
    borderRadius: 12,
    padding: 15,
  },
  topDeliverymanInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  topDeliverymanName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 12,
  },
  topDeliverymanDeliveries: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '600',
    marginLeft: 'auto',
    backgroundColor: `${colors.primary}15`,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  detailedCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 50,
    ...shadows.medium,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
    padding: 12,
    backgroundColor: `${colors.primary}08`,
    borderRadius: 12,
    margin: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 5,
  },
  statLabel: {
    fontSize: 13,
    color: colors.text,
    marginTop: 5,
    textAlign: 'center',
    fontWeight: '500',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 20,
    marginBottom: 15,
  },
  chart: {
    marginVertical: 15,
    borderRadius: 16,
    backgroundColor: colors.cardBackground,
    padding: 15,
    ...shadows.small,
  },
  listItem: {
    fontSize: 15,
    color: colors.textLight,
    marginBottom: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  motoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    ...shadows.small,
  },
  motoPlate: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 12,
  },
  motoCount: {
    fontSize: 14,
    color: colors.secondary,
    marginLeft: 'auto',
    backgroundColor: `${colors.secondary}15`,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    fontWeight: '600',
  },
  statusCard: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    ...shadows.medium,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 15,
  },
  statusInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${colors.primary}08`,
    padding: 12,
    borderRadius: 12,
  },
  orderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    backgroundColor: colors.background,
    padding: 12,
    borderRadius: 12,
  },
  orderIdText: {
    fontSize: 14,
    color: colors.textLight,
    marginLeft: 10,
    fontWeight: '500',
  },
  nameContainer: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: colors.cardBackground,
    borderRadius: 12,
    ...shadows.small,
  },
  name: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  starIcon: {
    marginHorizontal: 2,
  },
  ratingCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  ratingContent: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  averageRating: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 8,
  },
  totalRatings: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  recentOrdersCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  orderItem: {
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
    paddingVertical: 12,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  orderNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },  orderDate: {
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
    flex: 1,
  },
  orderDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  orderIcon: {
    marginRight: 8,
  },
  customerName: {
    fontSize: 14,
    color: '#666',
  },
  orderStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  statusText: {
    fontSize: 14,
    color: '#FF4B2B',
    fontWeight: '500',
  },
  dateFilterContainer: {
    padding: 16,
    backgroundColor: 'white',
    marginBottom: 16,
    borderRadius: 8,
  },
  dateFilterTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginBottom: 16,
  },
  filterButton: {
    padding: 12,
    borderRadius: 4,
    backgroundColor: '#F5F5F5',
    minWidth:65,
    alignItems: 'center',
  },
  filterButtonActive: {
    backgroundColor: '#FFE5E5',
  },
  filterButtonDisabled: {
    opacity: 0.5,
    backgroundColor: colors.border,
  },
  filterButtonText: {
    color: '#333',
  },
  customDateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateButton: {
    padding: 8,
    borderRadius: 4,
    backgroundColor: '#F5F5F5',
    flex: 0.48,
  },
  dateButtonText: {
    textAlign: 'center',
    color:'gray'
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalButton: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#FF4B2B',
    borderRadius: 4,
    width: '100%',
  },
  modalButtonText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  exportButton: {
    backgroundColor: '#FF4B2B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 30,
  },
  exportButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContents: {
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  modalButtons: {
    padding: 8,
  },
  cancelText: {
    color: '#FF4B2B',
    fontSize: 16,
  },
  confirmText: {
    color: '#FF4B2B',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Adicione estes estilos ao seu statsScreenStyles.ts existente

  deleteButtonContainer: {
    padding: 16,
    alignItems: 'flex-end', // Alinha o botão à direita
  },
  deleteButton: {
    backgroundColor: '#E53E3E',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  deleteButtonDisabled: {
    backgroundColor: '#CBD5E0',
    opacity: 0.7,
  },
  deleteButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 4,
  },
  deleteIcon: {
    marginRight: 4,
  },
  // Estilos do Modal
  modalOverlayD: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContentD: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 400,
  },
  modalTitleD: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    color: '#1A202C',
  },
  modalText: {
    fontSize: 14,
    color: '#4A5568',
    marginBottom: 8,
  },
  modalId: {
    fontSize: 14,
    fontWeight: '500',
    color: '#2D3748',
    marginBottom: 16,
    padding: 8,
    backgroundColor: '#EDF2F7',
    borderRadius: 4,
  },
  confirmationInput: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    fontSize: 14,
    color: '#2D3748',
  },
  modalButtonsD: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  cancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#EDF2F7',
  },
  cancelButtonText: {
    color: '#4A5568',
    fontSize: 14,
    fontWeight: '500',
  },
  confirmButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#E53E3E',
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  topDeliverymenContainer: {
    marginVertical:15
  },
  noOrdersText: { // Added noOrdersText style
    textAlign: 'center',
    color: colors.textLight,
    marginTop: 16,
    fontSize: 14,
  },
  cardHeader: { // Added cardHeader style
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10, // Adjust as needed
  },
  seeMoreButton: { // Added seeMoreButton style
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: `${colors.primary}1A`, // Light primary background
  },  seeMoreButtonText: { // Added seeMoreButtonText style
    color: colors.primary,
    fontSize: 13,
    fontWeight: '500',
  },
  pontoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 15,
    ...shadows.small,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },  pontoButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginLeft: 12,
    flex: 1,
  },
  recentOrdersTitle: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  realtimeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  realtimeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.success,
    marginRight: 6,
  },
  realtimeText: {
    fontSize: 12,
    color: colors.success,
    fontWeight: '500',
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  viewMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 75, 43, 0.1)',
  },
  viewMoreText: {
    fontSize: 12,
    color: '#FF4B2B',
    fontWeight: '500',
    marginRight: 4,
  },
  loadingTextContainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingMainText: {
    fontSize: 16,
    color: colors.text,
    textAlign: 'center',
    fontWeight: '500',
    marginBottom: 4,
  },
  loadingSubText: {
    fontSize: 13,
    color: colors.primary,
    textAlign: 'center',
    fontStyle: 'italic',
    opacity: 0.8,
  },
});

export default styles;